name: CI - Mon Premier Pipeline  # Nom du workflow

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - "backend/**"
      - "frontend/**"

  pull_request:
    branches: [ "main" ]

  schedule:
    - cron: "0 2 * * *"   # Exécution tous les jours à 2h du matin

  workflow_dispatch:      # Lancement manuel
